DragonBox/uplift

- CHANGELOG.md
> Preparing release for 1.0.0beta3

- CHANGELOG.md
> Preparing release for 1.0.0beta4

- CHANGELOG.md
- README.md
> Preparing release for 1.0.0beta5

- Assets/Plugins/Editor/Uplift/Common/SampleFile.cs
- Assets/Plugins/Editor/Uplift/MenuItems.cs
- Assets/Plugins/Editor/Uplift/Schemas/Extensions/UpliftSettings.cs
- Assets/Plugins/Editor/Uplift/Windows/SettingsWindow.cs
- Assets/Plugins/Editor/Uplift/Windows/SettingsWindow.cs.meta
Add settings editor window to be able to create/edit the settings file easily.
> Implement settings editor window

- Assets/Plugins/Editor/BuildTool/BuildLibraryData.cs
- Assets/Plugins/Editor/BuildTool/BuildPaths.cs
- Assets/Plugins/Editor/BuildTool/DllCompiler.cs
- Assets/Plugins/Editor/BuildTool/Helper.cs
- Assets/Plugins/Editor/BuildTool/UnityInstallation.cs
- Assets/Plugins/Editor/Uplift/Common/Cli.cs
- Assets/Plugins/Editor/Uplift/Common/FileSystemUtil.cs
- Assets/Plugins/Editor/Uplift/Common/SampleFile.cs
- Assets/Plugins/Editor/Uplift/Common/UnityPackageOpener.cs
- Assets/Plugins/Editor/Uplift/Common/VersionParser.cs
- Assets/Plugins/Editor/Uplift/DependencyResolution/DependencyHelper.cs
- Assets/Plugins/Editor/Uplift/DependencyResolution/TransitiveDependencySolver.cs
- Assets/Plugins/Editor/Uplift/Export/Exporter.cs
- Assets/Plugins/Editor/Uplift/Export/PackageExportData.cs
- Assets/Plugins/Editor/Uplift/Initialize.cs
- Assets/Plugins/Editor/Uplift/LogAggregator.cs
- Assets/Plugins/Editor/Uplift/MenuItems.cs
- Assets/Plugins/Editor/Uplift/Schemas/Extensions/InstalledPackage.cs
- Assets/Plugins/Editor/Uplift/Schemas/Extensions/Upbring.cs
- Assets/Plugins/Editor/Uplift/Schemas/Extensions/Upfile.cs
- Assets/Plugins/Editor/Uplift/Schemas/Extensions/UpliftSettings.cs
- Assets/Plugins/Editor/Uplift/Schemas/Repositories/FileRepository.cs
- Assets/Plugins/Editor/Uplift/Schemas/Repositories/GithubRepository.cs
- Assets/Plugins/Editor/Uplift/SourceControl/GitIgnorer.cs
- Assets/Plugins/Editor/Uplift/UpdateTool/Updater.cs
- Assets/Plugins/Editor/Uplift/Utils/GitHub.cs
- Assets/Plugins/Editor/Uplift/Windows/RawUpfileEditor.cs
- Assets/Plugins/Editor/Uplift/Windows/UpdateWindow.cs
- Assets/Plugins/Editor/Uplift/Windows/UpfileEditor.cs
For clarity and efficiency purpose.
> Cleanup: remove unused usings

- Assets/Plugins/Editor/Uplift/Common/FileSystemUtil.cs
- Assets/Plugins/Editor/Uplift/Schemas/Repositories/GithubRepository.cs
- Cache the Upset fetched from GithubRepository to speed up the repository reloading.
- Minor modifications to FileSystemUtil
> Add very basic caching for Upset fetching in GithubRepository

- CHANGELOG.md
- README.md
> Preparing release for 1.0.0beta6

- Assets/Plugins/Editor/Uplift/Initialize.cs
- Assets/Plugins/Editor/Uplift/MenuItems.cs
- Assets/Plugins/Editor/Uplift/UpliftManager.cs
- Assets/Plugins/Editor/Uplift/Windows/UpdateWindow.cs
> Fix upfile not refreshed before install

- Assets/Plugins/Editor/Uplift/Windows/UpdateWindow.cs
> Fix update window offering to update to old versions

- CHANGELOG.md
- README.md
> Preparing release for 1.0.0beta8

- CHANGELOG.md
- README.md
> Preparing release for 1.0.0beta10

- .github_changelog_generator
- Assets/Plugins/Editor/Uplift/About.cs
- DevelopmentTools/Rakefile
- README.md
> Preparing release for 1.0.0beta11

- CHANGELOG.md
- README.md
> Preparing release for 1.0.0beta13

- DevelopmentTools/Rakefile
I had some issues and wanted to test the upload without rebuilding.
> Build: split Rakefile for testing the release notes upload

- Assets/Plugins/Editor/Uplift/UpliftManager.cs
> Revert "Fix/lockfile/fix lockfile modifications when installing from lockfile"

- Assets/Plugins/Editor/Uplift/LockfFileManager.cs
- Assets/Plugins/Editor/Uplift/LockfFileManager.cs.meta
- Assets/Plugins/Editor/Uplift/LockfFileTracker.cs
- Assets/Plugins/Editor/Uplift/LogHandler.cs
- Assets/Plugins/Editor/Uplift/UpliftManager.cs
UpliftManger file contained many function related to lockfile. 
To make UpliftManager file clearer, all the lockfile related functions are moved in a LockfileManager file.
> Extract lockfile specific logic from UpliftManager

- CHANGELOG.md
- README.md
> Preparing release for 1.0.0beta15

- CHANGELOG.md
- README.md
> Preparing release for 1.0.0beta16

- .github_changelog_generator
- CHANGELOG.md
- README.md
> Preparing release for 1.0.0beta17

- CHANGELOG.md
- README.md
> Preparing release for 1.0.0beta18
