DragonBox/uplift

Assets/Plugins/Editor/Uplift/Common/UnityPackageOpener.cs, Assets/Plugins/Editor/Uplift/Common/UnityPackageOpener.cs.meta, Assets/Plugins/Editor/Uplift/Schemas/Repositories/FileRepository.cs
- Extract .unitypackage extraction from FileRepository to a new class UnityPackageOpener.
- Various cleaning of calls inside FileRepository
=> Refactor FileRepository

Assets/Plugins/Editor/Uplift/Common/FileSystemUtil.cs, Assets/Plugins/Editor/Uplift/Initialize.cs, Assets/Plugins/Editor/Uplift/LockfFileTracker.cs, Assets/Plugins/Editor/Uplift/LockfFileTracker.cs.meta, Assets/Plugins/Editor/Uplift/UpliftManager.cs
Instead of checking whether or not the project has been installed on editor launch with an environment variable containing `"true"`, the environment variable now stores the MD5 of the lockfile so it knows when the file has been changed, and when to trigger an installation.
This is useful for automated install on checkouts and pulls.
=> Keep track of the Upfile.lock MD5 to detect project changes

Assets/Plugins/Editor/Uplift/Common/VersionRequirements.cs, Assets/Plugins/Editor/Uplift/Testing/UnitTesting/VersionRequirementTest.cs
LoseVersionRequirement (version) and BoundedVersionRequirement
(version*) are not supposed to be conflicting as they should be
compatible in the BoundedVersionRequirement which is the more
restrictive of the two.
This behaviour was correctly happening when LoseVersionRequirement was
restricted to BoundedVersionRequirement but not the other way around,
so this fixes it.
Fixes #12
=> Fix Version requirement lose and bounded conflict

Assets/Plugins/Editor/BuildTool/BuildLibraryData.cs, Assets/Plugins/Editor/BuildTool/DllCompiler.cs, Assets/Plugins/Editor/BuildTool/UnityInstallation.cs, Assets/Plugins/Editor/Uplift/LogAggregator.cs, Gemfile.lock
This provide an actual fix for the issue #20, and revert unnecessary changes from 659c909
Fixes #20
=> Compiler: use defines to make sure that .unitypackage is built correctly

Assets/Plugins/Editor/Uplift/Windows/UpfileEditor.cs
The Edit Upfile window was failing because of the lack of support for the new GithubRepository. This fixes it by
- adding support for GithubRepositories
- handling unknown cases
=> Fix lack of support for unknown repositories in Upfile Editor window

.github_changelog_generator, Assets/Plugins/Editor/Uplift/About.cs, CHANGELOG.md, README.md
=> Preparing release for 1.0.0beta7

Assets/Plugins/Editor/Uplift/Export/Exporter.cs
Github does not support packages named with a '~' which causes a few
issues, notably while uploading assets named this way and trying to
detect if it has already been released.
=> Change package~name to package-name

Assets/Plugins/Editor/Uplift/Common/VersionRequirements.cs, Assets/Plugins/Editor/Uplift/Testing/UnitTesting/VersionRequirementTest.cs
In specifc scenarii (such as merging 0.9 and 0.9.4+) the requirements were not properly merged event though they are clearly compatible. This addresses it by adding this scenario to the MinimalVersionRequirement.RestrictTo(...)`.
=> Fix lose and minimal version requirement merge

Assets/Plugins/Editor/Uplift/Export/Exporter.cs, Assets/Plugins/Editor/Uplift/Export/PackageExportData.cs, Assets/Plugins/Editor/Uplift/Export/PackageExportDataInspector.cs, Assets/Plugins/Editor/Uplift/Export/PackageExportDataInspector.cs.meta, Assets/Plugins/Editor/Uplift/Windows/ExporterWindow.cs
The main goal of this is to clean the PackageExportData to separate the display of the data from the actual logic, in a backwards compatible way.
Besides cleaning, the goal of this is to enable:
- getting rid of the template Upset and allow dependency and configuration edition directly
- UI cleanup
=> Refactor ExportPackage definition

Assets/Plugins/Editor/Uplift/Schemas/Repositories/GithubRepository.cs
This does two things:
- Close the popup window when a failure occur not to leave the ugly popup
- Logs additional information
=> Cleaner failure when trying to download an asset

Assets/Plugins/Editor/Uplift/UpliftPreferences.cs
This addresses an issue where the preferences were seemingly not used. They were not loaded correctly before usage.
=> Make sure that the preferences are loaded before using them

Assets/Plugins/Editor/Uplift/Initialize.cs
Instead of logging `Upfile loading...` which is not that nice, log the used version of Uplift for better understanding.
=> Log current Uplift version on Initialize

Assets/Plugins/Editor/Uplift/Common/VersionRequirements.cs, Assets/Plugins/Editor/Uplift/UpliftManager.cs
When validating dependencies, the IVersionRequirement was not parsing the string completly (ie omitting the optional field in the version), resulting in improper validation.
This fixes the checks, and add better message in the situation where this failure appeared.
=> Fix: Better optional parameter parsing

Assets/Plugins/Editor/Uplift/MenuItems.cs
A lot of feedback tend to show that there was a confusion regarding what was doing what between "Debug/Install from lockfile" and "Install Dependencies". This moves the lockfile installation out of the debug section as it is not a debug-only feature and is used quite frequently.
Moreover, this clarifies the messages to better explain the difference between the installation methods.
=> Menu Items: Make installation from menu clearer

Assets/Plugins/Editor/Uplift/Common/VersionParser.cs, Assets/Plugins/Editor/Uplift/Common/VersionRequirements.cs, Assets/Plugins/Editor/Uplift/Testing/UnitTesting/VersionRequirementTest.cs, Assets/Plugins/Editor/Uplift/Testing/UnitTesting/VersionTest.cs
This introduces the new `RangeVersionRequirement` which enables to define more precise syntax such as `Version="a,b"` with `a <= version < b`.
This new requirement enables other requirements that were considered incompatibles to be so.
This PR also fixes #66 by correctly merging LoseVersionRequirements and included MinimalVersionRequirement as a more restrictive RangeVersionRequirement.
=> Introduce Range version requirement

Assets/Plugins/Editor/Uplift/UpliftManager.cs
There was an error happening sometimes when updating package : 
`System.InvalidOperationException: Operation is not valid due to the current state of the object`
It seemed to occurred when uplift tries to update a package which is not listed in the "UPFILE DEPENDENCIES" listed in Upfile.lock. Thus the search for the package definition failed. 
Small fix which solve problem while updating a package was to set the package definition to null in that case by using `FirstOrDefault` instead of `First` method. 
**NOTE :** This PR depends on [this PR](https://github.com/DragonBox/uplift/pull/71/commits)
I had a little trouble opening this pull request, but it should be fine by now.
=> Correct update package function to prevent error in First method

Assets/Plugins/Editor/Uplift/MenuItems.cs
The Package Export asset was not displayed after its creation. Users had to go and find the asset in the project files to edit it. Now it is displayed in the inspector after its creation.
=> Display PackageExport.asset after its creation

Assets/Plugins/Editor/Uplift/Export/Exporter.cs
Some using were missing in `Exporter.cs`.
I just added them.
=> Add missing usings

Assets/Plugins/Editor/Uplift/UpliftManager.cs
The Uplift Manager ran the depency solving algorithm in all cases of InstallDependencies, even when solving with `InstallStrategy.ONLY_LOCKFILE` which does not require the resolution.
This makes sure that this is not run when not needed.
=> UplfitManager: do not solve dependencies if InstallStrategy.ONLY_LOCKFILE

Assets/Plugins/Editor/Uplift/SourceControl/GitIgnorer.cs
=> GitIgnorer: do not register .meta files in the .gitignore

Assets/Plugins/Editor/Uplift/UpliftManager.cs
When running `UpliftManager.InstallPackages()`, several (solved) packages are solved at once and then passed for installation. However if the package already exist, it updates it to the expected version.
The issue is that this update then try to update the package dependencies in cascade, updating packages which shouldn't be.
=> Do not update dependencies when installing several dependencies at once
